---
# tasks file for ansible-role-cvmfs
#
#
- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ cvmfs_deb_dependencies }}"

- name: Check if cvmfs is installed 
  command: dpkg-query -W cvmfs
  register: reg_cvmfs_check_deb
  failed_when: reg_cvmfs_check_deb.rc > 1
  changed_when: reg_cvmfs_check_deb.rc == 1

- name: Check if cvmfs-config is installed
  command: dpkg-query -W cvmfs-config
  register: reg_cvmfs_config_check_deb
  failed_when: reg_cvmfs_config_check_deb.rc > 1
  changed_when: reg_cvmfs_config_check_deb.rc == 1

- name: Download cvmfs
  get_url:
    url: "{{ cvmfs_deb_url }}"
    dest: "/tmp/cvmfs.deb"
  when: reg_cvmfs_check_deb.rc == 1

- name: Download cvmfs-config
  get_url:
    url: "{{ cvmfs_deb_config_url }}"
    dest: "/tmp/cvmfs-config.deb"
  when: cvmfs_deb_config_url is defined and reg_cvmfs_config_check_deb.rc == 1

- name: Install cvmfs-config
  apt:
    deb: "/tmp/cvmfs-config.deb"
  when: cvmfs_deb_config_url is defined and reg_cvmfs_config_check_deb.rc == 1

- name: Install cvmfs
  apt:
    deb: "/tmp/cvmfs.deb"
  when: reg_cvmfs_check_deb.rc == 1

- name: Install autofs
  apt:
    name: autofs
    state: present

- name: add cvmfs user to fuse group
  user:
    name: cvmfs
    append: yes
    groups: fuse
