---
# tasks file for ansible-role-cvmfs
#
 - include_tasks: redhat.yml
   when: ansible_os_family == "RedHat"
 - include_tasks: debian.yml
   when: ansible_os_family == "Debian"
## Common tasks
 - name: lineinfile fuse.conf to enable user_allow_other
   lineinfile:
     dest: /etc/fuse.conf
     regexp: '^user_allow_other$'
     line: 'user_allow_other'
     backup: yes

 - name: add a cms.cern.ch.local if cms_site is defined
   template:
     src: cms.cern.ch.local
     dest: /etc/cvmfs/config.d/cms.cern.ch.local
     mode: 0644
   when: cms_site is defined
 
 - name: template cvmfs/default.local if none exists - no overwrite
   template: 
     src: default.local 
     dest: /etc/cvmfs/default.local 
     force: no 
     mode: 0644
   when: cvmfs_overwrite_default_local == False
 
 - name: template cvmfs/default.local if it exists - overwrites
   template:
     src: default.local
     dest: /etc/cvmfs/default.local
     force: yes
     mode: 0644
     backup: yes
   when: cvmfs_overwrite_default_local == True
 
 - name: ensure /etc/auto.master.d/ exists
   file: path=/etc/auto.master.d state=directory
 
 - name: template /etc/auto.master.d/cvmfs.autofs
   template:
     src: cvmfs.autofs
     dest: /etc/auto.master.d/cvmfs.autofs
     backup: yes
   when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 7) or ansible_os_family == "Debian"
   notify: restart autofs
   register: autofsconfig
 
 - name: ensure that autofs is running and enabled
   service:
     name: autofs
     state: started
     enabled: yes
   when: ansible_virtualization_type != "docker"
 
 - name: flush the handlers - so that autofs settings are applied before we run chksetup
   meta: flush_handlers
 
 - name: cvmfs_config chksetup which causes the playbook to fail when there are errors
   command: cvmfs_config chksetup
   register: cvmfschksetup
   failed_when: cvmfschksetup.rc != 0
   changed_when: false
   when: ansible_virtualization_type != "docker"
 
 #- name: print output of cvmfschksetup
 #  debug: var=cvmfschksetup["stdout"]
 #  when: cvmfschksetup.changed
 
 - name: check that the repo is mounted
   stat: path=/cvmfs/{{cvmfs_test_repo}}
   register: p
 
 - debug: msg="Can list cvmfs_test_repo"
   when: p.stat.isdir is defined and p.stat.isdir
 
