---
# tasks file for ansible-role-cvmfs
#
- name: download the CVMFS repo
  get_url: url=http://cvmrepo.web.cern.ch/cvmrepo/yum/cernvm.repo dest=/etc/yum.repos.d/cernvm.repo mode=0644

- name: install CVMFS gpg key
  rpm_key: key=http://cvmrepo.web.cern.ch/cvmrepo/yum/RPM-GPG-KEY-CernVM state=present

- name: Install FGCI repo 
  yum: pkg=http://idris.fgi.csc.fi/fgci7/x86_64/fgci/rpms/fgci-release7-1-1.el7.noarch.rpm
  when: ansible_distribution_major_version == "7"
  when: fgci_install == True

- name: Install FGCI CVMFS repofiles
  yum: name=cvmfs-repofiles-fgi state=present
  when: fgci_install == True

- name: Install CVMFS client EL6
  yum: name={{ item }} state=present
  with_items:
    - cvmfs-release
    - cvmfs-keys
    - cvmfs
    - cvmfs-init-scripts
    - cvmfs-auto-setup
  when: ansible_distribution_major_version == "6"

- name: Install CVMFS client EL7
  yum: name={{ item }} state=present
  with_items:
    - cvmfs-keys
    - cvmfs
    - cvmfs-config-default
  when: ansible_distribution_major_version == "7"

- name: add a cms.cern.ch.local if cms_site is defined
  template: src=cms.cern.ch.local dest=/etc/cvmfs/config.d/cms.cern.ch.local mode=0644
  when: cms_site is defined

# TODO: What if we do want to overwrite it?
- name: template cvmfs/default.local if none exists
  template: src=default.local dest=/etc/cvmfs/default.local force=no mode=0644

- name: template /etc/auto.master.d/cvmfs.autofs EL7 only
  template: src=cvmfs.autofs dest=/etc/auto.master.d/cvmfs.autofs backup=yes
  register: autofsconfig
  when: ansible_distribution_major_version == "7"

- name: ensure that autofs is running and enabled
  service: name=autofs state=started enabled=yes

- name: ensure that autofs is restarted after configchange
  service: name=autofs state=restarted
  when: autofsconfig.changed

- name: cvmfs_config chksetup which causes the playbook to fail when there are errors
  command: cvmfs_config chksetup
  register: cvmfschksetup

- name: print output of cvmfschksetup
  debug: var=cvmfschksetup["stdout"]

- name: check that the repo is mounted
  stat: path=/cvmfs/{{cvmfs_test_repo}}
  register: p

- debug: msg="Can list cvmfs_test_repo"
  when: p.stat.isdir is defined and p.stat.isdir
